[2024-09-17T17:45:08.359+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-17T17:45:08.404+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rasa_data_ingestion_dag.define_hashes manual__2024-09-17T15:16:10.285347+00:00 [queued]>
[2024-09-17T17:45:08.425+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rasa_data_ingestion_dag.define_hashes manual__2024-09-17T15:16:10.285347+00:00 [queued]>
[2024-09-17T17:45:08.426+0000] {taskinstance.py:2865} INFO - Starting attempt 9 of 10
[2024-09-17T17:45:08.459+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): define_hashes> on 2024-09-17 15:16:10.285347+00:00
[2024-09-17T17:45:08.480+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'rasa_data_ingestion_dag', 'define_hashes', 'manual__2024-09-17T15:16:10.285347+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/rasa_data_ingestion_dag.py', '--cfg-path', '/tmp/tmpx47kkrby']
[2024-09-17T17:45:08.485+0000] {standard_task_runner.py:105} INFO - Job 74: Subtask define_hashes
[2024-09-17T17:45:08.489+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1570) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-17T17:45:08.491+0000] {standard_task_runner.py:72} INFO - Started process 1571 to run task
[2024-09-17T17:45:08.577+0000] {task_command.py:467} INFO - Running <TaskInstance: rasa_data_ingestion_dag.define_hashes manual__2024-09-17T15:16:10.285347+00:00 [running]> on host aca847883b6e
[2024-09-17T17:45:08.781+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Eric Silveira' AIRFLOW_CTX_DAG_ID='rasa_data_ingestion_dag' AIRFLOW_CTX_TASK_ID='define_hashes' AIRFLOW_CTX_EXECUTION_DATE='2024-09-17T15:16:10.285347+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-17T15:16:10.285347+00:00'
[2024-09-17T17:45:08.783+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-17T17:45:08.810+0000] {base.py:84} INFO - Retrieving connection 'conn_db_***'
[2024-09-17T17:45:08.834+0000] {base.py:84} INFO - Retrieving connection 'conn_db_origem'
[2024-09-17T17:45:08.837+0000] {rasa_data_ingestion_dag.py:95} ERROR - Ocorreu um erro: connection to server at "postgres_ingestion" (172.22.0.4), port 5440 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-09-17T17:45:08.837+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-17T17:45:08.859+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-17T17:45:08.860+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=***_data_ingestion_dag, task_id=define_hashes, run_id=manual__2024-09-17T15:16:10.285347+00:00, execution_date=20240917T151610, start_date=20240917T174508, end_date=20240917T174508
[2024-09-17T17:45:08.916+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-17T17:45:08.953+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-17T17:45:08.956+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
