[2024-09-17T18:35:33.666+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-17T18:35:33.702+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rasa_data_ingestion_dag.define_hashes manual__2024-09-17T15:16:10.285347+00:00 [queued]>
[2024-09-17T18:35:33.721+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rasa_data_ingestion_dag.define_hashes manual__2024-09-17T15:16:10.285347+00:00 [queued]>
[2024-09-17T18:35:33.722+0000] {taskinstance.py:2865} INFO - Starting attempt 17 of 18
[2024-09-17T18:35:33.749+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): define_hashes> on 2024-09-17 15:16:10.285347+00:00
[2024-09-17T18:35:33.770+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'rasa_data_ingestion_dag', 'define_hashes', 'manual__2024-09-17T15:16:10.285347+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/rasa_data_ingestion_dag.py', '--cfg-path', '/tmp/tmpoq7y6nyr']
[2024-09-17T18:35:33.775+0000] {standard_task_runner.py:105} INFO - Job 83: Subtask define_hashes
[2024-09-17T18:35:33.779+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=576) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-17T18:35:33.780+0000] {standard_task_runner.py:72} INFO - Started process 577 to run task
[2024-09-17T18:35:33.864+0000] {task_command.py:467} INFO - Running <TaskInstance: rasa_data_ingestion_dag.define_hashes manual__2024-09-17T15:16:10.285347+00:00 [running]> on host 4b36eb9de04e
[2024-09-17T18:35:34.054+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Eric Silveira' AIRFLOW_CTX_DAG_ID='rasa_data_ingestion_dag' AIRFLOW_CTX_TASK_ID='define_hashes' AIRFLOW_CTX_EXECUTION_DATE='2024-09-17T15:16:10.285347+00:00' AIRFLOW_CTX_TRY_NUMBER='17' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-17T15:16:10.285347+00:00'
[2024-09-17T18:35:34.056+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-17T18:35:34.078+0000] {base.py:84} INFO - Retrieving connection 'conn_db_***'
[2024-09-17T18:35:34.102+0000] {base.py:84} INFO - Retrieving connection 'conn_db_origem'
[2024-09-17T18:35:34.112+0000] {rasa_data_ingestion_dag.py:93} ERROR - Ocorreu um erro: relation "events" does not exist
LINE 3:                     FROM events;
                                 ^

[2024-09-17T18:35:34.112+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-17T18:35:34.131+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-17T18:35:34.132+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=***_data_ingestion_dag, task_id=define_hashes, run_id=manual__2024-09-17T15:16:10.285347+00:00, execution_date=20240917T151610, start_date=20240917T183533, end_date=20240917T183534
[2024-09-17T18:35:34.199+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-17T18:35:34.236+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-17T18:35:34.239+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
