[2024-09-17T19:43:48.746+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-17T19:43:48.767+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rasa_data_ingestion_dag.verify_and_create_table manual__2024-09-17T19:43:15.495969+00:00 [queued]>
[2024-09-17T19:43:48.777+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rasa_data_ingestion_dag.verify_and_create_table manual__2024-09-17T19:43:15.495969+00:00 [queued]>
[2024-09-17T19:43:48.777+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 3
[2024-09-17T19:43:48.790+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): verify_and_create_table> on 2024-09-17 19:43:15.495969+00:00
[2024-09-17T19:43:48.801+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'rasa_data_ingestion_dag', 'verify_and_create_table', 'manual__2024-09-17T19:43:15.495969+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/rasa_data_ingestion_dag.py', '--cfg-path', '/tmp/tmpqued4w8d']
[2024-09-17T19:43:48.804+0000] {standard_task_runner.py:105} INFO - Job 100: Subtask verify_and_create_table
[2024-09-17T19:43:48.804+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2172) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-17T19:43:48.804+0000] {standard_task_runner.py:72} INFO - Started process 2173 to run task
[2024-09-17T19:43:48.854+0000] {task_command.py:467} INFO - Running <TaskInstance: rasa_data_ingestion_dag.verify_and_create_table manual__2024-09-17T19:43:15.495969+00:00 [running]> on host 4b36eb9de04e
[2024-09-17T19:43:48.939+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Eric Silveira' AIRFLOW_CTX_DAG_ID='rasa_data_ingestion_dag' AIRFLOW_CTX_TASK_ID='verify_and_create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-17T19:43:15.495969+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-17T19:43:15.495969+00:00'
[2024-09-17T19:43:48.940+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-17T19:43:48.954+0000] {base.py:84} INFO - Retrieving connection 'conn_db_***'
[2024-09-17T19:43:48.968+0000] {base.py:84} INFO - Retrieving connection 'conn_db_origem'
[2024-09-17T19:43:48.977+0000] {rasa_data_ingestion_dag.py:22} INFO - =
[2024-09-17T19:43:48.977+0000] {rasa_data_ingestion_dag.py:23} INFO - ==============START LOGGING===============
[2024-09-17T19:43:48.977+0000] {rasa_data_ingestion_dag.py:24} INFO - A tabela 'events' n√£o existe.
[2024-09-17T19:43:48.978+0000] {rasa_data_ingestion_dag.py:25} INFO - ==============END LOGGING===============
[2024-09-17T19:43:48.978+0000] {rasa_data_ingestion_dag.py:26} INFO - =
[2024-09-17T19:43:48.999+0000] {rasa_data_ingestion_dag.py:22} INFO - =
[2024-09-17T19:43:49.000+0000] {rasa_data_ingestion_dag.py:23} INFO - ==============START LOGGING===============
[2024-09-17T19:43:49.000+0000] {rasa_data_ingestion_dag.py:24} INFO - ['id', 'sender_id', 'type_name', 'timestamp', 'intent_name', 'action_name', 'data']
[2024-09-17T19:43:49.000+0000] {rasa_data_ingestion_dag.py:25} INFO - ==============END LOGGING===============
[2024-09-17T19:43:49.000+0000] {rasa_data_ingestion_dag.py:26} INFO - =
[2024-09-17T19:43:49.000+0000] {rasa_data_ingestion_dag.py:22} INFO - =
[2024-09-17T19:43:49.000+0000] {rasa_data_ingestion_dag.py:23} INFO - ==============START LOGGING===============
[2024-09-17T19:43:49.000+0000] {rasa_data_ingestion_dag.py:24} INFO - ['bigint', 'bigint', 'character varying', 'double precision', 'character varying', 'character varying', 'text']
[2024-09-17T19:43:49.001+0000] {rasa_data_ingestion_dag.py:25} INFO - ==============END LOGGING===============
[2024-09-17T19:43:49.001+0000] {rasa_data_ingestion_dag.py:26} INFO - =
[2024-09-17T19:43:49.001+0000] {rasa_data_ingestion_dag.py:22} INFO - =
[2024-09-17T19:43:49.001+0000] {rasa_data_ingestion_dag.py:23} INFO - ==============START LOGGING===============
[2024-09-17T19:43:49.001+0000] {rasa_data_ingestion_dag.py:24} INFO - False
[2024-09-17T19:43:49.001+0000] {rasa_data_ingestion_dag.py:25} INFO - ==============END LOGGING===============
[2024-09-17T19:43:49.001+0000] {rasa_data_ingestion_dag.py:26} INFO - =
[2024-09-17T19:43:49.001+0000] {rasa_data_ingestion_dag.py:118} ERROR - Ocorreu um erro: cannot access local variable 'query_create_table' where it is not associated with a value
[2024-09-17T19:43:49.002+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-17T19:43:49.012+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-17T19:43:49.012+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=***_data_ingestion_dag, task_id=verify_and_create_table, run_id=manual__2024-09-17T19:43:15.495969+00:00, execution_date=20240917T194315, start_date=20240917T194348, end_date=20240917T194349
[2024-09-17T19:43:49.060+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-17T19:43:49.079+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-17T19:43:49.080+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
