[2024-09-17T19:19:20.040+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-17T19:19:20.080+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rasa_data_ingestion_dag.verify_and_create_table manual__2024-09-17T15:16:10.285347+00:00 [queued]>
[2024-09-17T19:19:20.099+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rasa_data_ingestion_dag.verify_and_create_table manual__2024-09-17T15:16:10.285347+00:00 [queued]>
[2024-09-17T19:19:20.100+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-17T19:19:20.144+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): verify_and_create_table> on 2024-09-17 15:16:10.285347+00:00
[2024-09-17T19:19:20.165+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'rasa_data_ingestion_dag', 'verify_and_create_table', 'manual__2024-09-17T15:16:10.285347+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/rasa_data_ingestion_dag.py', '--cfg-path', '/tmp/tmpm23ifqaf']
[2024-09-17T19:19:20.170+0000] {standard_task_runner.py:105} INFO - Job 90: Subtask verify_and_create_table
[2024-09-17T19:19:20.174+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1372) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-17T19:19:20.176+0000] {standard_task_runner.py:72} INFO - Started process 1373 to run task
[2024-09-17T19:19:20.258+0000] {task_command.py:467} INFO - Running <TaskInstance: rasa_data_ingestion_dag.verify_and_create_table manual__2024-09-17T15:16:10.285347+00:00 [running]> on host 4b36eb9de04e
[2024-09-17T19:19:20.458+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Eric Silveira' AIRFLOW_CTX_DAG_ID='rasa_data_ingestion_dag' AIRFLOW_CTX_TASK_ID='verify_and_create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-17T15:16:10.285347+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-17T15:16:10.285347+00:00'
[2024-09-17T19:19:20.460+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-17T19:19:20.485+0000] {base.py:84} INFO - Retrieving connection 'conn_db_***'
[2024-09-17T19:19:20.511+0000] {base.py:84} INFO - Retrieving connection 'conn_db_origem'
[2024-09-17T19:19:20.534+0000] {rasa_data_ingestion_dag.py:22} INFO - =
[2024-09-17T19:19:20.534+0000] {rasa_data_ingestion_dag.py:23} INFO - ==============START LOGGING===============
[2024-09-17T19:19:20.535+0000] {rasa_data_ingestion_dag.py:24} INFO - A tabela 'events' não existe.
[2024-09-17T19:19:20.535+0000] {rasa_data_ingestion_dag.py:25} INFO - ==============END LOGGING===============
[2024-09-17T19:19:20.535+0000] {rasa_data_ingestion_dag.py:26} INFO - =
[2024-09-17T19:19:20.559+0000] {rasa_data_ingestion_dag.py:22} INFO - =
[2024-09-17T19:19:20.560+0000] {rasa_data_ingestion_dag.py:23} INFO - ==============START LOGGING===============
[2024-09-17T19:19:20.561+0000] {rasa_data_ingestion_dag.py:24} INFO - A tabela é essa
[2024-09-17T19:19:20.561+0000] {rasa_data_ingestion_dag.py:25} INFO - ==============END LOGGING===============
[2024-09-17T19:19:20.561+0000] {rasa_data_ingestion_dag.py:26} INFO - =
[2024-09-17T19:19:20.562+0000] {rasa_data_ingestion_dag.py:22} INFO - =
[2024-09-17T19:19:20.562+0000] {rasa_data_ingestion_dag.py:23} INFO - ==============START LOGGING===============
[2024-09-17T19:19:20.563+0000] {rasa_data_ingestion_dag.py:24} INFO - [('id', 'bigint'), ('sender_id', 'bigint'), ('type_name', 'character varying'), ('timestamp', 'double precision'), ('intent_name', 'character varying'), ('action_name', 'character varying'), ('data', 'text')]
[2024-09-17T19:19:20.564+0000] {rasa_data_ingestion_dag.py:25} INFO - ==============END LOGGING===============
[2024-09-17T19:19:20.564+0000] {rasa_data_ingestion_dag.py:26} INFO - =
[2024-09-17T19:19:20.564+0000] {rasa_data_ingestion_dag.py:110} ERROR - Ocorreu um erro: name 'result_query_columns_table' is not defined
[2024-09-17T19:19:20.565+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-17T19:19:20.585+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-17T19:19:20.586+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=***_data_ingestion_dag, task_id=verify_and_create_table, run_id=manual__2024-09-17T15:16:10.285347+00:00, execution_date=20240917T151610, start_date=20240917T191920, end_date=20240917T191920
[2024-09-17T19:19:20.677+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-17T19:19:20.728+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-17T19:19:20.732+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
